### ISSUE TITLE
Real life test:

### ISSUE THREAD

**Issue by joost0004** [nsp-team3/north-sea-port-team-3#68]
frequency tabel maken

**Comment by zefanjajobse** [comment]
6350 tile requests open sea maps – mag mishandeld worden, heeft grote cache systeem
9760 tile requests street maps – ^^
140 bridges api – https://waterkaart.net/
220 get vessels api – https://www.myshiptracking.com/
20 detailed vessel info – https://www.myshiptracking.com/
Images 14 bruggen – https://waterkaart.net/
/uur
